### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by tugrulyatagan** [networkedsystems/lora-ns3#1]
Hi,

I followed these steps to build this ns-3 module:
`wget https://www.nsnam.org/release/ns-allinone-3.28.tar.bz2`
`tar xvjf ns-allinone-3.28.tar.bz2`
`cd ns-allinone-3.28/ns-3.28/src/`
`git clone https://github.com/networkedsystems/lora-ns3.git lora`
`cd ../`
`./waf --enable-examples --enable-tests configure`
`./waf`

But I get following error on last step:
`source not found: 'model/lora-tsch-net-device.cc' in bld(features=['cxx', 'cxxshlib', 'ns3module'], ns3_dir_location='src/lora', ...`

I guess some of the lora-ns3 module source files are missing on current codebase.

Thanks,
Tugrul

**Comment by DingXiang12** [comment]
Hi, did you solve this problem? I also encountered now.

**Comment by networkedsystems** [comment]
You are right. I added all files. It should compile now.

**Comment by nmatni** [comment]
I got 
`Traceback (most recent call last):
  File "/tmp/ns-allinone-3.28/ns-3.28/.waf3-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Node.py", line 312, in ant_iter
    raise StopIteration
`
Just after ./waf --enable-examples --enable-tests configure
